"""create_sellers

Revision ID: 3beb540e8c96
Revises: ed150c691172
Create Date: 2026-05-24 20:41:09.297784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3beb540e8c96'
down_revision: Union[str, Sequence[str], None] = 'ed150c691172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_ecommerce', sa.String(length=128), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=False),
    sa.Column('app_key_enc', sa.Text(), nullable=True),
    sa.Column('app_token_enc', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.String(length=64), nullable=True),
    sa.Column('estado_keys', sa.Enum('activo', 'inactivo', 'vencido', name='estadokeys'), nullable=False),
    sa.Column('integracion', sa.String(length=255), nullable=True),
    sa.Column('vendiendo', sa.Boolean(), nullable=False),
    sa.Column('analista', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_ecommerce'),
    sa.UniqueConstraint('seller_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    # ### end Alembic commands ###
