"""create_crud_operations_and_rows

Revision ID: aebf175eabcb
Revises: 3beb540e8c96
Create Date: 2026-05-24 20:59:05.439403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aebf175eabcb'
down_revision: Union[str, Sequence[str], None] = '3beb540e8c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crud_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('operacion', sa.String(length=1), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('sellers_scope', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('filtros_usados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('total_success', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('duration_secs', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crud_operation_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=512), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['crud_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crud_operation_rows')
    op.drop_table('crud_operations')
    # ### end Alembic commands ###
